name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  dio: ^5.6.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.1
